/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lamazooproj;

import accesseBDD.LogIn;
import accesseBDD.Connexion;
import accesseBDD.sql.CheckAccesse;
import accesseBDD.sql.VeterinaireSQL;
import java.awt.Color;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class JffLamaZOO extends javax.swing.JFrame {
    private LogIn accesse;
    private CheckAccesse accesseChecker;
    private VeterinaireSQL veterinaireSQL;
    private Connexion lamazoo;
    private boolean accesseError;
    private HashMap<Integer, String[]> listDesAnimals;
    private ArrayList<ArrayList<Object>> listDesSoignants;
    private int animalId;
    private ArrayList animalInfo;
    private JffCommentaire jffCommentaire;
    private JffHistoriqueSoin jffHistoriqueSoin;
    /**
     * Creates new form LamaZOO
     */
    public JffLamaZOO() {
        initComponents();
    }
    public JffLamaZOO(LogIn accesse) throws IOException {
        lamazoo = new Connexion("Localhost", "db_lamazoo", "publicVisiteur", "mdpVisiteur");
        initComponents();
        this.accesse = accesse;
        accesseChecker = new CheckAccesse(accesse, lamazoo);
        veterinaireSQL = new VeterinaireSQL(accesse, lamazoo);
        if(accesseChecker.check()) {
            listDesAnimals = veterinaireSQL.getListDesAnimals();
            remplirTableau(listDesAnimals);
            listDesSoignants = veterinaireSQL.getSoignant();
            remplirSoignant(listDesSoignants);
        } else {
            accesseError = true;
        }   
    }
    
    private void badToken() {
        JffAuthentification jffAuthentification = new JffAuthentification();
        jffAuthentification.setVisible(true);
        this.dispose();
    }
    
    public boolean getAccesseError() {
        return accesseError;
    }
    public void styleComm() {
        if(!jTFComm.getText().equals("0")) {
            jPComm.setBackground(new Color(204, 255, 204));
        } else {
            jPComm.setBackground(new Color(204, 204, 204));
        }
    }
    
    private void remplirTableau(HashMap<Integer, String[]> listDesAnimals) {
        DefaultTableModel model = (DefaultTableModel) jTAnimeaux.getModel();
        listDesAnimals.forEach((key, value) -> {
            model.addRow(new Object[] {key, value[1], value[0]});
        }); 
    }
    
    
    private void remplirSoignant(ArrayList<ArrayList<Object>> listDesSoignants) {
        for(ArrayList<Object> listObject : listDesSoignants) {
            jCBSoignant.addItem(String.valueOf(listObject.get(1)) + " " + String.valueOf(listObject.get(2)));
        } 
    }
    
    public javax.swing.JTextField getTFComm() {
        return jTFComm;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTAnimeaux = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNomAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFSurnomAnimal = new javax.swing.JTextField();
        jTFPoidsAnimal = new javax.swing.JTextField();
        jTFDecesAnimal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFPaysAnimal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFNaissanceAnimal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLTitreSoin = new javax.swing.JLabel();
        jTFTitreSoin = new javax.swing.JTextField();
        jLSoin = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTPSoin = new javax.swing.JTextPane();
        jBHistorique = new javax.swing.JButton();
        jBEnvoyerSoin = new javax.swing.JButton();
        jPComm = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTFComm = new javax.swing.JTextField();
        jBComm = new javax.swing.JButton();
        jCBSoignant = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTAnimeaux.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Surnom", "Nom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAnimeaux.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTAnimeaux.getTableHeader().setReorderingAllowed(false);
        jTAnimeaux.setRowHeight(2, 100);
        jTAnimeaux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAnimeauxMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTAnimeaux);
        if (jTAnimeaux.getColumnModel().getColumnCount() > 0) {
            jTAnimeaux.getColumnModel().getColumn(0).setMinWidth(0);
            jTAnimeaux.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTAnimeaux.getColumnModel().getColumn(0).setMaxWidth(0);
            jTAnimeaux.getColumnModel().getColumn(1).setResizable(false);
            jTAnimeaux.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Nom:");

        jLabel2.setText("Surnom:");

        jTFNomAnimal.setEditable(false);

        jLabel3.setText("Poids:");

        jTFSurnomAnimal.setEditable(false);

        jTFPoidsAnimal.setEditable(false);

        jTFDecesAnimal.setEditable(false);

        jLabel4.setText("Pays d'origine:");

        jLabel5.setText("Date de naissance:");

        jTFPaysAnimal.setEditable(false);

        jLabel6.setText("Date du décès:");

        jTFNaissanceAnimal.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Soin:");

        jPanel2.setBackground(new java.awt.Color(222, 217, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setEnabled(false);

        jLTitreSoin.setText("Titre:");
        jLTitreSoin.setEnabled(false);

        jTFTitreSoin.setEnabled(false);

        jLSoin.setText("Description:");
        jLSoin.setEnabled(false);

        jTPSoin.setEnabled(false);
        jScrollPane3.setViewportView(jTPSoin);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLSoin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLTitreSoin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFTitreSoin)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTitreSoin)
                    .addComponent(jTFTitreSoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSoin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jBHistorique.setText("Historique des soins");
        jBHistorique.setEnabled(false);
        jBHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistoriqueActionPerformed(evt);
            }
        });

        jBEnvoyerSoin.setText("Envoyer");
        jBEnvoyerSoin.setEnabled(false);
        jBEnvoyerSoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnvoyerSoinActionPerformed(evt);
            }
        });

        jPComm.setBackground(new java.awt.Color(204, 204, 204));
        jPComm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPComm.setToolTipText("");
        jPComm.setLayout(new java.awt.BorderLayout());

        jLabel7.setText(" Nouveaux commentaires:  ");
        jPComm.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jTFComm.setEditable(false);
        jTFComm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPComm.add(jTFComm, java.awt.BorderLayout.CENTER);

        jBComm.setText("Commentaires");
        jBComm.setEnabled(false);
        jBComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCommActionPerformed(evt);
            }
        });

        jCBSoignant.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBEnvoyerSoin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jCBSoignant, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBHistorique)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTFNomAnimal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFSurnomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFPoidsAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFPaysAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNaissanceAnimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFDecesAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPComm, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBComm)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSurnomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFPoidsAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFPaysAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFDecesAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFNaissanceAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPComm, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jBComm))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBHistorique)
                                .addComponent(jCBSoignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEnvoyerSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTAnimeauxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAnimeauxMouseClicked
        if(accesseChecker.check()) {
            animalId = (int)jTAnimeaux.getValueAt(jTAnimeaux.getSelectedRow(), 0);
            animalInfo = veterinaireSQL.getInfoDesAlimeaux(animalId);
            jTFNomAnimal.setText(animalInfo.get(0).toString());
            jTFSurnomAnimal.setText(animalInfo.get(1).toString());
            jTFPoidsAnimal.setText(animalInfo.get(2).toString());
            jTFPaysAnimal.setText(animalInfo.get(3).toString());
            jTFNaissanceAnimal.setText(animalInfo.get(4).toString());
            jTFDecesAnimal.setText(animalInfo.get(5).toString());

            jTFComm.setText(String.valueOf(veterinaireSQL.getNouveauxComm(animalId)));
            styleComm();
            jBComm.setEnabled(true);
            if(jffCommentaire != null) {
                jffCommentaire.setVisible(false);
            } 
            if(jffHistoriqueSoin != null) {
                jffHistoriqueSoin.setVisible(false);
            }
            jffCommentaire = new JffCommentaire(accesse, animalId, veterinaireSQL, lamazoo, accesseChecker, jPComm, jTFComm);
            jffHistoriqueSoin = new JffHistoriqueSoin();
            jTFTitreSoin.setEnabled(true);
            jTPSoin.setEnabled(true);
            jLTitreSoin.setEnabled(true);
            jLSoin.setEnabled(true);
            jBHistorique.setEnabled(true);
            jBEnvoyerSoin.setEnabled(true);
            jCBSoignant.setEnabled(true);
        } else {
            badToken();
        }
    }//GEN-LAST:event_jTAnimeauxMouseClicked

    private void jBCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCommActionPerformed
        if(jffCommentaire == null) {
            jffCommentaire = new JffCommentaire(accesse, animalId, veterinaireSQL, lamazoo, accesseChecker, jPComm, jTFComm);
            jffCommentaire.setVisible(true);
        } else {
            jffCommentaire.setVisible(true);
        }
    }//GEN-LAST:event_jBCommActionPerformed

    private void jBHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistoriqueActionPerformed
        jffHistoriqueSoin = new JffHistoriqueSoin(accesse, animalId, veterinaireSQL, lamazoo, accesseChecker);
        jffHistoriqueSoin.setVisible(true);
    }//GEN-LAST:event_jBHistoriqueActionPerformed

    private void jBEnvoyerSoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnvoyerSoinActionPerformed
        if(!jTFTitreSoin.getText().equals("") & !jTPSoin.getText().equals("")) {
            int confirm = JOptionPane.showOptionDialog(this,
          "Volez vous envoyer un soin?", "Exit", JOptionPane.YES_NO_OPTION,
       JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (confirm == JOptionPane.YES_OPTION) {
                veterinaireSQL.setSoin(jTFTitreSoin.getText(), jTPSoin.getText(),  animalId, (int)listDesSoignants.get(jCBSoignant.getSelectedIndex()).get(0));
                jTFTitreSoin.setText("");
                jTPSoin.setText("");
            } 
        } else {
            JOptionPane.showMessageDialog(null, "Remplissez la title ou la discription.");
            
        }
    }//GEN-LAST:event_jBEnvoyerSoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JffLamaZOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JffLamaZOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JffLamaZOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JffLamaZOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JffLamaZOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBComm;
    private javax.swing.JButton jBEnvoyerSoin;
    private javax.swing.JButton jBHistorique;
    private javax.swing.JComboBox<String> jCBSoignant;
    private javax.swing.JLabel jLSoin;
    private javax.swing.JLabel jLTitreSoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPComm;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTAnimeaux;
    private javax.swing.JTextField jTFComm;
    private javax.swing.JTextField jTFDecesAnimal;
    private javax.swing.JTextField jTFNaissanceAnimal;
    private javax.swing.JTextField jTFNomAnimal;
    private javax.swing.JTextField jTFPaysAnimal;
    private javax.swing.JTextField jTFPoidsAnimal;
    private javax.swing.JTextField jTFSurnomAnimal;
    private javax.swing.JTextField jTFTitreSoin;
    private javax.swing.JTextPane jTPSoin;
    // End of variables declaration//GEN-END:variables
}
